# Generated by Django 6.0 on 2025-12-10 10:46
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
